### ISSUE TITLE
MODUS3_CA ppd file has errors

### ISSUE THREAD

**Issue by nmuggli** [CustomOpenSource/CUPS_drivers#1]
When running `cupstestppd MODUS3_CA.ppd`, I see the following errors:
```
      **FAIL**  DefaultCutterMode 4FullCutEndDoc does not exist.
      **FAIL**  Bad DefaultCutterMode 4FullCutEndDoc
                REF: Page 40, section 4.5.
```

I assume the default needs to be `1FullCutEndPage` or `2FullCutEndDoc`.

If that is the correct fix, I assume the code may need to be updated [here](https://github.com/CustomOpenSource/CUPS_drivers/blob/main/MODUS3_CA/src/rasterToPrn.c#L493) and [here](https://github.com/CustomOpenSource/CUPS_drivers/blob/main/MODUS3_CA/src/rasterToPrn.c#L511).

**Comment by CustomOpenSource** [comment]
Thank  you for reporting the bug.
The fix is in the last commit https://github.com/CustomOpenSource/CUPS_drivers/commit/6e3bf4f66a4b700e0e3726dbe60070c1bfaff559 as you suggested.
