### ISSUE TITLE
Update Manufacturer in H400_H350.ppd file

### ISSUE THREAD

**Issue by nmuggli** [CustomOpenSource/CUPS_drivers#2]
The Manufacturer in the H400_H350.ppd file is listed as `HP`.  Should this be `CUSTOM` to match all the other PPD files?

Also, `HP` shows up in the `1284DeviceID` field and in the `ModelName` field.  In the other PPD files the `ModelName` does not include the manufacturer - I don't know if this one should be different or not.

**Comment by CustomOpenSource** [comment]
This printer model was developed by Custom in partnership with HP.  It's correct that the Manufacturer in this case is HP.

**Comment by CustomOpenSource** [comment]
This printer model was developed by Custom in partnership with HP. It's correct that the Manufacturer in this case is HP.
